site_name:        Optim.jl
repo_url:         https://github.com/JuliaNLSolvers/Optim.jl/
site_description: Pure Julia implementations of optimization algorithms.
site_author:      JuliaNLSolvers

theme: windmill

markdown_extensions:
#  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

extra_css:
  - assets/Documenter.css

docs_dir: 'build'

pages:
    - Home: 'index.md'
    - Tutorials:
        - Minimizing a function: 'user/minimization.md'
        - Gradients and Hessians: 'user/gradientsandhessians.md'
        - Configurable Options: 'user/config.md'
        - Linesearch: 'algo/linesearch.md'
        - Algorithm choice: 'user/algochoice.md'
        - Preconditioners: 'algo/precondition.md'
        - Complex optimization: 'algo/complex.md'
        - Manifolds: 'algo/manifolds.md'
        - Tips and tricks: 'user/tipsandtricks.md'
        - Interior point Newton: 'examples/generated/ipnewton_basics.md'
        - Maximum likelihood estimation: 'examples/generated/maxlikenlm.md'
        - Conditional maximum likelihood estimation: 'examples/generated/rasch.md'
    - Algorithms:
        - Gradient Free:
            - Nelder Mead: 'algo/nelder_mead.md'
            - Simulated Annealing: 'algo/simulated_annealing.md'
            - Simulated Annealing w/ bounds: 'algo/samin.md'
            - Particle Swarm: 'algo/particle_swarm.md'
#                - Univariate:
#                    - Brent's Method: 'algo/brent.md'
#                    - Golden Section: 'algo/goldensection.md'
        - Gradient Required:
            - 'Conjugate Gradient': 'algo/cg.md'
            - 'Gradient Descent': 'algo/gradientdescent.md'
            - '(L-)BFGS': 'algo/lbfgs.md'
            - 'Acceleration': 'algo/ngmres.md'
        - Hessian Required:
            - Newton: 'algo/newton.md'
            - Newton with Trust Region: 'algo/newton_trust_region.md'
            - Interior point Newton: 'algo/ipnewton.md'
    - Contributing: 'dev/contributing.md'
    - License: 'LICENSE.md'
